export const SEND_PHOTOS_START = 'PHOTOS/SEND_START'
export const SEND_PHOTOS_SUCCESS = 'PHOTOS/SEND_SUCCESS'
export const SEND_PHOTOS_FAILURE = 'PHOTOS/SEND_FAILURE'

export const GET_PHOTOS_START = 'PHOTOS/GET_START'
export const GET_PHOTOS_SUCCSS = 'PHOTOS/GET_SUCCSS'
export const GET_PHOTOS_FAILURE = 'PHOTOS/GET_FAILURE'